---
- name: Install package for python env
  become: yes
  apt:
    name:
      - python3-pip
    update-cache: yes

- name: Create Directory
  file:
    path: ./server
    state: directory

- name: Install apache2
  become: yes
  apt:
    name:
      - apache2
    update-cache: yes
    state: latest